### ISSUE TITLE
Stuff to translate

### ISSUE THREAD

**Issue by Tiippex** [bittiez/TotalTracker#22]
Timeformat in Playtime
Player in Header of each table
Search button
Search field

**Comment by bittiez** [comment]
Timeformat in Playtime -> [Already done](https://github.com/bittiez/TotalTracker/blob/master/web/lang/en.php#L23-L25)
Player in Header of each table -> [Already done](https://github.com/bittiez/TotalTracker/blob/master/web/lang/en.php#L22)

I will add the other two soon, thanks!

You just need to update your language file, I can't update translations as I don't know other languages so if you want to provide translations just find a way to send me them(Here, or discord works good)
