### ISSUE TITLE
Update Checker

### ISSUE THREAD

**Issue by Tiippex** [bittiez/TotalTracker#34]
Hey I have some problems with the update checker:
![Error](http://tiippex.de/pics/i/sbcan.png)

**Comment by bittiez** [comment]
That error won't effect how the plugin works, it's just an update checker.
I am no longer working on my minecraft plugins so sadly I won't be looking
into this to fix it, sorry!

**Comment by Tiippex** [comment]
Meh, thats a bit said, could you add a small function in the config.yml to disable the update checker?

**Comment by bittiez** [comment]
Well sadly, I'm not updating my plugins anymore, but if you feel like
diving into java or know someone who makes/edits plugins, these are the
lines you would need to remove to stop the update checking process:
https://github.com/bittiez/TotalTracker/blob/master/src/US/bittiez/TotalTracker/main.java#L110-L113
