### ISSUE TITLE
Make the reload buttons clickable with animation

### ISSUE THREAD

**Issue by Tiippex** [bittiez/TotalTracker#9]
Atm the buttons doesent show the cursor for clicking...
and perhaps you can add a rotation when they reload...

**Comment by bittiez** [comment]
Notes for myself: 
- Add on hover background color 
- Change to images with a loading and not loading
- On click change to loading
- Once loaded change back

**Comment by bittiez** [comment]
I'm going to mark this as complete with the changes made in the last version https://github.com/bittiez/TotalTracker/releases/tag/1.19.0
 88f26d355f027d754f0c00e9a7f4f5ae44df8609
If you feel like those changes weren't enough, feel free to make another issue!

**Comment by Tiippex** [comment]
the hover function does still not work...

**Comment by bittiez** [comment]
It works for me, it's not animated though, I added a background color on-hover to make it more apparent that it's a button. I just couldn't find a good looking reload animation I liked, so I decided to just add a background-color
